const MixPanelEvents = {
  LOGGED_IN_ENTRY: 'Logged In Entry Page',
  LOGGED_OUT_ENTRY: 'Logged Out Entry Page',
  WATCHED_VIDEO: 'Video Watch',
  WATCHED_SECOND_VIDEO: 'Video Watch + 1',
  WATCHED_THIRD_VIDEO: 'Video Watch + 2',
  WATCHED_FOURTH_VIDEO: 'Video Watch + 3',
  WATCHED_VIDEO_PERCENT_25: 'VW - 25%',
  WATCHED_VIDEO_PERCENT_50: 'VW - 50%',
  WATCHED_VIDEO_PERCENT_75: 'VW - 75%',
  WATCHED_VIDEO_PERCENT_100: 'VW - 100%',
  SHARED_VIDEO: 'Video Share',
  REGISTRATION_REQUEST: 'Register Link',
  FAVORITE_REGISTRATION_REQUEST: 'Favorite - Registration Request',
  PLAYLIST_REGISTRATION_REQUEST: 'Playlist - Registration Request',
  SUBSCRIBE_REGISTRATION_REQUEST: 'Subscribe - Registration Request',
  REGISTRATION_SUBMIT: 'Registration Submit',
  KEYWORD_SEARCH: 'Keyword Search',
  ADD_TO_FAVORITES: 'Add to Favorites',
  ADD_TO_PLAYLIST: 'Add to Playlist',
  SUBSCRIBE_REQUEST: 'Subscribe',
  UNSUBSCRIBE_REQUEST: 'Unsubscribe',
  INCOMING_REDIRECTION_REQUEST: 'Loads Discover Tags',
  VISIT_TOOL: 'Tool Visited',
  PAGE_LOADED: 'Entry Page',
  LISTEN_PODCAST: 'Listen Podcast',
  DEEP_DIVE_TRIGGERED: 'DEEP_DIVE',
};

export default MixPanelEvents;
