export const GET_PARTNERS_SUCCESS = 'GET_PARTNERS_SUCCESS';
export const GET_PARTNERS_FAILURE = 'GET_PARTNERS_FAILURE';
export const POST_CONTACT_US_MAIL_SUCCESS = 'POST_CONTACT_US_MAIL_SUCCESS';
export const POST_CONTACT_US_MAIL_FAILURE = 'POST_CONTACT_US_MAIL_FAILURE';
export const POST_BECOME_PARTNER_MAIL_SUCCESS = 'POST_BECOME_PARTNER_MAIL_SUCCESS';
export const POST_BECOME_PARTNER_MAIL_FAILURE = 'POST_BECOME_PARTNER_MAIL_FAILURE';
